spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #指定数据源类型,如果没有指定,则sb默认使用hikari
    url: jdbc:mysql://192.168.0.239:3306?useSSL=false
    username: root
    password: Thj_2017
    driver:
      class:
        name: com.mysql.jdbc.Driver

db:
  url: jdbc:mysql://192.168.0.239:3306?useSSL=false
  username: root
  password: Thj_2017
  mysql:
    driver: com.mysql.jdbc.Driver

##指向mapper的xml文件位置(名字不能更改,否则将读取不到配置文件)
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml